### ISSUE TITLE
USER STORY: Vote and add comment in online poll with or without anonymity

### ISSUE THREAD

**Issue by hysinh** [hysinh/My-First-Agile-Project#3]
In order **provide feedback on best times for running, best track, etc** as a **runner**, I can **anonymously vote and add a comment to a website poll**.

## Acceptance Criteria:

- Acceptance Criteria 1: Option for anonymity should be provided as a checkbox
- Acceptance Criteria 2: The checkbox should be "checked" by default
- Acceptance Criteria 3: The option for anonymity should appear next to the submit button
- Acceptance Criteria 4: After submitting, the default submission confirmation should be adjusted to include the user name.

### Tasks:
- [ ] Task 1: Create the HTML/CSS for poll form.
- [ ] Task 2: Add checkbox next to submission button.
- [ ] Task 3: Make checkbox "checked" as default
- [ ] Task 4: Make sure individual user data is not saved with poll data when checkbox is "checked" and form is submitted.
- [ ] Task 5: Create the HTML/CSS for the default submission confirmation.
- [ ] Task 6: Add user name field to display in submission confirmation.
- [ ] Task 7: Test functionality
