### ISSUE TITLE
USER STORY: Add votes and keep records of all previous polls including voting details

### ISSUE THREAD

**Issue by hysinh** [hysinh/My-First-Agile-Project#4]
In order **analyze online poll data** as a **website administrator**, I can **add votes and keep records of all previous polls including voting details**.

## Acceptance Criteria:
* Acceptance Criteria 1: Administrator can record and store data from all previous polls via csv file upload.
* Acceptance Criteria 2: Each poll submission saves the poll data to the database.
* Acceptance Criteria 3: Administrator can create a new poll.

### Tasks:
- [ ] Task 1: Create API to connect poll submission to database.
- [ ] Task 2: Save poll data to database each time a poll is completed and submitted
- [ ] Task 3: Allow Administrator to put an expiration date on the poll.
- [ ] Task 4: Reserve space on the homepage with a message that says "Stay Tuned, a new poll is coming soon" when no poll is active
- [ ] Task 5: Create a javascript function to validate the expiry date is at least after 3 days.
- [ ] Task 6: Create a job to check expired polls every day at 11:59pm and hide them.
- [ ] Task 7: Update the controller function
- [ ] Task 8: Update unit test scripts
- [ ] Test 9: Test functionality
